---
language: ruby
rvm:
- 2.2.5
- 2.3.1
services:
- postgresql
before_script:
- "./bin/setup"
script:
- bundle exec rake spec
- bundle exec rubocop --fail-level C
gemfile:
- gemfiles/rails_3.2.22.gemfile
- gemfiles/rails_4.2.7.gemfile
- gemfiles/rails_5.0.0.gemfile
