---
language: ruby
rvm:
- 2.3.4
- 2.4.0
services:
- postgresql
before_script:
- "./bin/setup"
script:
- bundle exec rake spec
- bundle exec rubocop --fail-level C
gemfile:
- gemfiles/rails_4.2.8.gemfile
- gemfiles/rails_5.1.1.gemfile
